### PR TITLE
add missing test for match key filtering

### PR DESCRIPTION
**Pull request by kmichel-aiven**

### CODE REVIEW

**Review by alanfranz — APPROVED** [review]
I still think that we shouldn't use conditionals in parametrized tests (I'd prefer a MY_KEY and an expected field) but it's better to have the test than not having it.

**Review by alanfranz — APPROVED** [review]
lgtm

**Comment by alanfranz** [comment]
I cannot merge and I cannot add other people as reviewers.

**Review by rikonen — APPROVED** [review]

**Comment by rikonen** [comment]
Hmm, for whatever reason I also cannot merge. I have been able to merge journalpump pull requests in the past.

**Review by staaldraad — APPROVED** [review]

**Pull request merged**
